name: Update JSON File

on:
  push:
    branches:
      - main  # Change this to match your branch name

jobs:
  update_json:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'


    - name: Run Python script
      run: python update_json.py
