name: Manual workflow
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup python
      uses: actions/setup-python@v5
    - name: Install dependencies
      run: |
         pip install --upgrade pip
    - name: Get changed files
      id: changed-files
      run: |
        git fetch origin main
        git diff --name-only origin/main...HEAD > changed_files.txt
        echo "::set-output name=changes::$(cat changed_files.txt)
    - name: Display changed files
      run: cat changed_files.txt
    - name: Run Python script with changed files
      if: steps.changed-files.outputs.changes # Check if there are changes
      run: |
        changed_files=$(cat changed_files.txt)
        python3 ex.py "$changed_files"
