name: Manual workflow

on:
  pull_request:
    paths:
      - 'conf/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
      - name: Install dependencies
        run: |
          pip install --upgrade pip
      - name: Get changed files
        id: changed-files-specific
        uses: tj-actions/changed-files@v40
        with:
          files: |
            conf/**
      - name: Run appropriate script
        if: ${{ steps.changed-files-specific.outputs.any_changed == 'true' }}
        run: |
          python3 validate.py --changed_file="${{ steps.changed-files-specific.outputs.all_changed_files }}"

